image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE: registry.gitlab.com/jakewright/home-automation-device-registry

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE:latest .
    - docker push $IMAGE:latest
    - docker build -f Dockerfile-arm --pull -t $IMAGE:arm .
    - docker push $IMAGE:arm
